### ISSUE TITLE
format flag day

### ISSUE THREAD

**Issue by posix4e** [Hoverbear/raft-rs#120]
Now that we have rust fmt in it's time to clean up all the code in raft-rs. That means breaking all of the pull requests. Let's pick a day and do it right for everyone!

**Comment by posix4e** [comment]
@Hoverbear

**Comment by Hoverbear** [comment]
@danburkert do you have any pending PRs?

@james-darkfox you have #88, I think it's no longer needed or has been covered. Can we close that?

I'm a-okay to do this any day once we know those two things.

**Comment by danburkert** [comment]
👍 from me.  I'm curious what's changed in rust-fmt recently?

**Comment by posix4e** [comment]
Nothing really changed. We just decided that it was possible to rust format
On Mon, May 2, 2016 at 2:42 PM Dan Burkert <notifications@github.com> wrote:

> 👍 from me. I'm curious what's changed in rust-fmt recently?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Hoverbear/raft-rs/issues/120#issuecomment-216373125>
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by Hoverbear** [comment]
It's now more integrated and considered more de-facto!

**Comment by posix4e** [comment]
https://github.com/Hoverbear/raft-rs/pull/121

**Comment by james-darkfox** [comment]
@Hoverbear #88 has not been covered, and the patch reduces processing required.

https://github.com/Hoverbear/raft-rs/blob/master/src/server.rs#L355-L370

Note that in the current code the process is:

- Insert the connection into the slab
- Try to register and hope it passes; if not
  - Remove the connection from the slab

vs

- Reserve slot / token
- Attempt to register the token / connection
- On success insert; else do nothing
- Peer stream gets dropped and connection is reset

In either case. Continue with the reformat and I'll take another look into getting the Entry API into the slab in mio again.

**Comment by Hoverbear** [comment]
Okay so I can accept this reformat?

**Comment by posix4e** [comment]
I talked to him it's fine
On Fri, May 13, 2016 at 10:07 PM Andrew Hobden <notifications@github.com>
wrote:

> Okay so I can accept this reformat?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Hoverbear/raft-rs/issues/120#issuecomment-219201129>
>
-- 
Sent from my mobile 4045076749
Alex Newman
