### ISSUE TITLE
Encrypted communication

### ISSUE THREAD

**Issue by droundy** [Hoverbear/raft-rs#131]
I know there is a lot of complexity in this, but it would be lovely to have support for some sort of encrypted communication.

**Comment by Hoverbear** [comment]
I'm not sure what benefit this would yield. Raft itself is not resistant to byzantine failure and there is nothing in this code preventing you from encrypting the data you're passing around. If you're worried about the metadata consider running this over a VPN.

PS: Please be aware this is basically unmaintained. You may be interested in https://github.com/pingcap/tikv
