### ISSUE TITLE
Raft Update Post

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft-rs#45]
I'm planning on doing a Raft update post, I'd like to talk about recent progress, changes, patterns we've found, etc.

Please feel encouraged to suggest topics and things to discuss!

* [x] `wrapped_enum` pattern - @james-darkfox 
* [x] `scoped_log` crate - @james-darkfox / @dcb
* [ ] Message handling - @hoverbear / @dcb
* [ ] Elections work - @dcb
* [x] @homu - @hoverbear
* [x] Coveralls - @hoverbear
* [ ] Meetup - @erickt
* [ ] State Machine impl
* [ ] Store impl
* [ ] Testing
* [x] Examples

**Comment by james-darkfox** [comment]
DarkFox
-------

- Improved error handling (wrapped_enum)
- Improved logging (scoped_log with dcb)
  - Possibility for improving with a syntax extension.
- Connection no longer tracking token
- Contributors extended

**Comment by Hoverbear** [comment]
@james-darkfox @huonw I posted about your new crates today: http://hoverbear.org/2015/07/16/raft-new-crates/

**Comment by james-darkfox** [comment]
`wrapped_enum` usage example is invalid.

pub enum -> variants aren't documented. See james-darkfox/rs-wrapped_enum-macro#1

**Comment by james-darkfox** [comment]
https://github.com/james-darkfox/rs-scoped_log/commit/9a1585317e78ffcd47b3b6ddd5cf6c51e7bfc530

**Comment by Hoverbear** [comment]
Updated!

**Comment by Hoverbear** [comment]
@erickt Do you know when the meetup will be announced?
