### ISSUE TITLE
Clear connection send queues on state change

### ISSUE THREAD

**Issue by danburkert** [Hoverbear/raft-rs#55]
All messages to be delivered to remote peers from the local `Replica` are added to a send queue, and asynchronously processed as individual TCP streams become writable.  When the local `Replica`'s state changes, these queues should be cleared.  Note that if a message is partially sent, then it should still be sent, since the receiving peer has no way to handle partially sent messages.

Justification for clearing the queue for each possible state change:

|Old State|New State|Action|
|---|---|---|
|Follower|Candidate|no messages should be queued to begin with|
|Candidate|Leader|only `RequestVoteRequest`s should be queued, and they are no longer necessary|
|Candidate|Follower|only `RequestVoteRequest`s are queued, and they are no longer valid|
|Leader|Follower|only `AppendEntryReqeuest`s should be queued, and they are no longer valid|

**Comment by Hoverbear** [comment]
We should also clear on `inconsistentPrevEntry` as we know that all future commands sent will fail as well and we need to roll them back and catch them up.
