### ISSUE TITLE
Raft Meetup @ Moz HQ

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft-rs#74]
Let's discuss content and schedule!

**Meeting Date:** August 26th, 7:00 PM
http://www.meetup.com/Rust-Bay-Area/events/219696985/

cc @danburkert @erickt @ycoady @posix4e @ongardie @dwrensha

If you're on the above list (or me) you're invited and welcome to present! Just say what you wanna talk about.

Possible things to discuss:

* **Why** distributed consensus matters. (5-10mins) @ycoady
* Raftscope with leader elections / LogCabin Experience (20mins) @ongardie
* Why Raft? Why not `___`?
* Component breakdown (Log, State Machine, Consensus, Server, Client) (15-20mins) @hoverbear
* Stepping Stones to make Rust a go-to Distributed Systems language @danburkert 
* Raft Applications and uses. @posix4e 
* TBD: @dwrensha

**Comment by Hoverbear** [comment]
@ongardie has said he'll be joining us and would be talk about Raft! He mentioned specifically Raftscope and Logcabin experience. He hinted there were some lessons from writing LogCabin in C++ that might be of interest to Rust users.

**Comment by erickt** [comment]
cc @brson

Great! Glad to have such interest in the talk. Normally our talks are between 60-120 minutes, so since we do have a lot of interest in people speaking, we need to be careful with our time budget. Evenly split 2 hours we've got 24 minutes per person. Is anyone planning on talking longer or shorter than that?

**Comment by ongardie** [comment]
First, let me link to the meetup page: http://www.meetup.com/Rust-Bay-Area/events/219696985/

I guess the question is how much we want/need to say about Raft itself. I'm happy to give a RaftScope-based talk on the whole algorithm, as I usually do. I've been forced to keep it within 24 minutes before ([ATC video](https://www.usenix.org/conference/atc14/technical-sessions/presentation/ongaro)), but I'd probably lose some folks that way. Talking so much about Raft in general might be overkill, however: it may be that understanding how Raft works isn't necessary here. On the other hand, it may help set up background for the other talks, or it may get people excited about distributed systems. I'm happy to do what you guys think makes the most sense for the audience.

I don't know how much @ycoady has to say on the matter, but I'd guess he can only say so much about why consensus matters before running out of words, so maybe that'd be a shorter talk.

If I come after that, most of my intro is taken care of, and I can talk about the replicated state machine approach to building consensus-based systems, do the Raft Overview slide, and then maybe just go over leader election in RaftScope. I usually spend about 5 minutes inside RaftScope on leader election. Then I can pop out of that, say that I've developed a C++ implementation of Raft called [LogCabin](https://github.com/logcabin/logcabin/), and do a slide or two on what was good and bad about using C++/tie it back to Rust. That's a lot of ground to cover, but maybe that'd stay within 20min or so.

**Comment by Hoverbear** [comment]
@ongardie I'm thinking @ycoady will have a fairly short intro, she's my advisor on this project so I definitely want to make sure she has space and I think she's a fantastic speaker. She teaches Distributed Systems here at the University of Victoria.

> If I come after that, most of my intro is taken care of, and I can talk about the replicated state machine approach to building consensus-based systems, do the Raft Overview slide, and then maybe just go over leader election in RaftScope.

That sounds perfect. I'm sure me and @danburkert will be talking more about the other details of Raft as we discuss how things work in code.

Thanks for being engaged on this! I can't wait to meet you!

**Comment by ycoady** [comment]
Absolutely!  I can be < 5 mins---this is fantastic---I had better go back and give @hoverbear a higher grade in that course... :)

**Comment by Hoverbear** [comment]
@ycoady I don't know if you can! I did pretty good. :)

**Comment by ongardie** [comment]
Cool. Also, @ycoady, are you teaching Raft already in your course? If so, we should list it on the Raft website, and if not, sad. https://raftconsensus.github.io/#courses

**Comment by Hoverbear** [comment]
@ycoady She didn't last time! Don't worry, I plugged Raft and we had 3 protects using it!

**Comment by erickt** [comment]
Hey everyone, I just heard we aren't able to get the room for August 27, but we could August 26 or 28. Would either of those days work for you all?

**Comment by danburkert** [comment]
Either of those dates works for me.

 - Dan

**Comment by ongardie** [comment]
Either works for me.

**Comment by ycoady** [comment]
@hoverbear definitely got https://github.com/ycoady/UVic-Distributed-Systems all aboard Raft before we hit Paxos---so it was game over, and the projects took it over from there!  Definitely on for the fall @ongardie, and @hoverbear is putting together a poster submission for SOSP on the Rust implementation (in his ample spare time!?)

**Comment by Hoverbear** [comment]
@erickt I arrive in San Fran at 3:00PM on the 26th! I think the 26th can work for me if it's at 7:00 still. I depart at noon on the 28th so that doesn't work for me at all.

**Comment by erickt** [comment]
We've locked in the meetup date to the 26th.

**Comment by ongardie** [comment]
@ycoady @Hoverbear cool, I'm gonna try to make it to SOSP this year as well.

**Comment by Hoverbear** [comment]
@ongardie Awesome!

**Comment by Hoverbear** [comment]
Me and @posix4e talked about him maybe discussing various applications of Raft. This might be a good opening and fill the spot where we have "Why Raft?"

**Comment by erickt** [comment]
Meetup's been [announced](http://www.meetup.com/Rust-Bay-Area/events/219696985/)! Tell your friends and loved ones!

**Comment by erickt** [comment]
Please let me know if you want me to tweak your subjects.

**Comment by ongardie** [comment]
@erickt: can you reorder @ycoady's talk to come first?

@Hoverbear @danburkert: can we call this project something other than simply "Raft"? In terms of branding, I'd like the name Raft to refer to the algorithm and the overall community, not to any particular implementation. (I'd also expect that as t approaches infinity, this probably won't be the only Raft implementation in Rust.) Hoverbear/Raft, Hoverbear's Raft would be fine by me but seem unfair to Dan. Hovercraft? It's not quite as cool as Hoverbear, but well.

**Comment by Hoverbear** [comment]
Actually I was thinking about the naming earlier and agree with you!

Itd be good to keep it in theme of servo/piston/etc... Junction maybe? Dan is on vacation for a bit, can we delay this for him? I can open a seperate issue.

**Comment by ongardie** [comment]
Cool, yeah, can definitely wait for Dan to get back.

**Comment by Hoverbear** [comment]
@posix4e / @dwrensha Any word on if/what you'll be talking about?

**Comment by posix4e** [comment]
I think I'll be discussing c5's use of raft and other raft applications.

On Thu, Aug 13, 2015, 13:34 Andrew Hobden <notifications@github.com> wrote:

> @posix4e <https://github.com/posix4e> / @dwrensha
> <https://github.com/dwrensha> Any word on if/what you'll be talking about?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hoverbear/raft/issues/74#issuecomment-130772735>.
>
-- 

Sent from my mobile 5045076749
Alex Newman

**Comment by erickt** [comment]
Hey y'all! I've been asked by Mozilla to ask you all if you're doing slides, and if so, are you using 4/3 or 16/9 widescreen slides.

**Comment by ongardie** [comment]
@erickt I'm doing slides (reveal.js) and raftscope (http://raft.github.io/raftscope/). Happy to use whichever aspect ratio works best with their setup (let me know).

Also, can you move @ycoady's talk before mine?

**Comment by Hoverbear** [comment]
@erickt Myself and @posix4e are using http://slides.com/, so probably 16x9?

**Comment by erickt** [comment]
@ongardie: Yep, I'll change the order. Sorry I missed your comment. Anyone else want to change their order?

**Comment by Hoverbear** [comment]
@erickt I'd like a large double double please.

**Comment by erickt** [comment]
@Hoverbear: want that wild style?

**Comment by erickt** [comment]
@ongardie: I think 16:9 will be fine. Do you have a URL for your slides?

@Hoverbear / @danburkert / @posix4e: Same for you three.

**Comment by Hoverbear** [comment]
@erickt http://slides.com/hoverbear/raft-rs#/

**Comment by ycoady** [comment]
@erickt http://slides.com/ycoady/a-long-long-time-ago/

**Comment by erickt** [comment]
@Hoverbear + @ycoady: You both get a :star: and a :star2:

**Comment by posix4e** [comment]
https://slides.com/alexnewman-2/raft-for-realz

On Tue, Aug 25, 2015, 15:08 Erick Tryzelaar <notifications@github.com>
wrote:

> @Hoverbear <https://github.com/Hoverbear> + @ycoady
> <https://github.com/ycoady>: You both get a [image: :star:] and a [image:
> :star2:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hoverbear/raft-rs/issues/74#issuecomment-134756457>.
>
-- 

Sent from my mobile 5045076749
Alex Newman

**Comment by danburkert** [comment]
@erickt my slides will be at http://slides.com/danburkert/simple-kv

**Comment by ongardie** [comment]
@erickt: sorry for the last minute post, my slides are at https://ongardie.net/static/raft-mozilla/ , visualization in the middle of my talk (will eat your CPU) is at https://raft.github.io/raftscope-replay/ , PDF fallback for slides (I don't trust web browsers) is at https://ongardie.net/static/raft-mozilla.pdf .

**Comment by Hoverbear** [comment]
That was freaking awesome everyone! :)

**Comment by foodhype** [comment]
I had to catch a Lyft ride. At the end, Diego was showing us a very interesting slide deck that included info about some of the more nuanced design decisions he made while designing log cabin. @danburkert did he mention where he had that slide deck hosted?

I enjoyed that meetup. I might write test cases--or at least a design doc on testing infrastructure for consensus algorithms--for raft-rs at some point.

**Comment by ongardie** [comment]
That was awesome. All of the other talks were great, thanks everyone!

@foodhype, I had pulled up the performance section in my dissertation and http://logcabin.github.io/talk/#/segmentedstorage when talking with @danburkert

**Comment by ycoady** [comment]
Thank you all---that was a blast!  Please come and visit our rock anytime you are in the neighbourhood!

**Comment by Hoverbear** [comment]
Yup! Open invitation to anyone from the meetup (or really, Rust community) to visit Victoria. I'll show you around and help you find some good places to eat etc!

**Comment by erickt** [comment]
Thank you so much everyone! That was great fun.
