### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft-rs#79]
As discussed in #74!

Thinking we should maintain a similar theme to other rust projects like Servo, Piston, etc.

Possible suggestions:

* Hovercraft
* Junction - Raft is responsible for applying commands to a replicated state machine, like a junction box.
* Replicator - Raft Replicates!
* rs-raft / raft-rs / rust-raft / raft-rust

## Votes
If you are a [contributor](https://github.com/Hoverbear/raft/graphs/contributors) or not please let us know what you favor. Majority is 5 in this cluster, or 4 if the 4 top contributors agree.

@hoverbear - `raft-rs`
@danburkert - `raft-rs`
@james-darkfox - `TODO`
@tschottdorf - `raft-rs`
@ongardie - `hovercraft`
(Others)

**Comment by james-darkfox** [comment]
Mind having rational aside each suggestion?

Also suggestion:

- rs-raft: simply states that it is a raft implementation in rust.
- liferaft: raft as a consensus algorithm will attempt to keep the application alive, despite partitions and network unreliability.

**Comment by Hoverbear** [comment]
@james-darkfox My personal feeling is something related to a machine part like piston/servo. I added that to the issue.

**Comment by james-darkfox** [comment]
Gotcha.

**Comment by jakerr** [comment]
I like fun names, but I also think it's really nice when possible, to allude to what the project is about or to its origins. For that reason I really like "Hovercraft" it's fun / catchy but also easy to remember as "Hoverbear's Raft Implementation". Also it has lots of potential for a cool logo!

**Comment by ycoady** [comment]
+1!

**Comment by james-darkfox** [comment]
hover c raft sounds like hoverbear's C raft implementation

**Comment by Hoverbear** [comment]
Maybe if we had C bindings it'd be suitable.

**Comment by Hoverbear** [comment]
After discussing a bit today I think that the right path is to take the `raft` crate name on Crates.io and name the project `raft-rs`... I'm open to permutations on that though.

Based off the fact that that Serde uses `serde-rs`... https://github.com/serde-rs/serde

**Comment by Hoverbear** [comment]
@james-darkfox brought up that in many cases packaging uses rs-raft style. (Posting because I think he's off now)

**Comment by erickt** [comment]
hovercraft is adorable. it's got your name and raft mashed in together!

**Comment by Hoverbear** [comment]
Also want to flag that https://crates.io/crates/raft does exist @mrhooray has it.

**Comment by james-darkfox** [comment]
Is there any process to transfer ownership? I.e. Add you as an owner, then revoke his own owner status?

**Comment by ongardie** [comment]
@james-darkfox, based on http://doc.crates.io/crates-io.html, I don't think so:
> Crate names are allocated on a first-come-first-serve basis. Once a crate name is taken it cannot be used for another crate.

**Comment by ongardie** [comment]
Rather, I guess you can probably do what you're saying of adding a new owner, but it probably needs to remain the "same" crate from crates.io's point of view.

**Comment by danburkert** [comment]
I agree we should probably rename the repo to something like 'raft-rs'.  It would be great if we could get the raft crate, there is a [process](http://doc.crates.io/crates-io.html#cargo-owner) for sharing/transferring ownership, but it would be up to @mrhooray whether he wanted to do that.  The existing raft crate is completely empty (nothing in lib.rs and no other rust files), and doesn't seem to be an associated repository.

**Comment by stefanpenner** [comment]
Hovercraft -> hoverraft

**Comment by james-darkfox** [comment]
As I said; and @danburkert linked to; once ownership is transferred - then hoverbear can own raft. This will have the side affect of requiring that we have a higher version number than @mrhooray 's current raft.

@ongardie Crates.io only cares for the crate name and the owners. The only "same" crate that comes into play is the version number and the crate-name.

**Comment by dwrensha** [comment]
I just want to say, "Hovercraft" -> "Hovercraft's Consensus Reaching And Fault Tolerant".
Or "Hoverbear's consensus reacher and fault tolerator".

**Comment by james-darkfox** [comment]
First feels like it is missing a noun at the end. Second seems like the system is a 'tolerator'.

**Comment by Hoverbear** [comment]
@dwrensha Wow, ends up as HCRAFT?

Those are rather neat.

**Comment by Hoverbear** [comment]
I'm going to shoot @mrhooray and email and ask him if he's planning to utilize the namespace.

**Comment by mrhooray** [comment]
yo guys, i initially wanted to implement raft protocol but got distracted to some other problems
already added @Hoverbear to owner

**Comment by mrhooray** [comment]
version wise wouldn't be an issue since the I left 0.0.0 there
would love to get some time and contribute to this library/crate :)

**Comment by danburkert** [comment]
Thanks, @mrhooray.  We're always looking for more contributors if you are still interested in raft.

**Comment by Hoverbear** [comment]
Thank you @mrhooray !

**Comment by Hoverbear** [comment]
@danburkert @james-darkfox @tschottdorf please let us know your final vote. :)

Anyone else is welcome as well. I'd like to close voting on the 21st at noon (Pacific) and make the change.

**Comment by ongardie** [comment]
In case it wasn't clear, I vote for hovercraft! This happened yesterday:
```
git clone https://github.com/Hoverbear/raft/ hovercraft
```

**Comment by Hoverbear** [comment]
@ongardie But what is the "c"????

**Comment by tschottdorf** [comment]
I like `raft-rs` for the current term and will vote `hovercraft` if there's a next term without entries committed in the current one.

**Comment by erickt** [comment]
@Hoverbear, you'll just have to figure that out. The community has spoken.

**Comment by ongardie** [comment]
@Hoverbear, you don't need to explain every single letter in every single name.  What the hell is "Raft", anyway?

**Comment by ongardie** [comment]
@erickt I'd like to think the community is larger than just me.

**Comment by Hoverbear** [comment]
@ongardie Robust Applied Functioning Terms.

**Comment by ongardie** [comment]
Here's what we came up with in the RAMCloud group meeting in 2012:

![raftnames](https://cloud.githubusercontent.com/assets/463856/9343087/b54d1e80-45b4-11e5-8d91-84c7dc714d1f.jpg)

**Comment by erickt** [comment]
@ongardie I was also including @dwrensha, @jakerr, and myself :)

**Comment by erickt** [comment]
@ongardie: haha "BestPaper". I would have loved to have read that paper.

**Comment by Hoverbear** [comment]
@erickt Maybe "c" is the community.

**Comment by danburkert** [comment]
I vote for `raft-rs`, with `raft` being the crates.io name.

**Comment by Hoverbear** [comment]
Renaming!
